version: '3.8'

services:
  ai-sci-gen:
    build: .
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: your_openai_api_key
      DATABASE_URL: sqlite:///./ai_sci_gen.db
    volumes:
      - ./app:/app
